document.writeln("<style>");
document.writeln("    body {");
document.writeln("        min-width: 1200px;");
document.writeln("        font-family: 微软雅黑;");
document.writeln("        color: #333;");
document.writeln("        background: #ffffff;");
document.writeln("    }");
document.writeln("");
document.writeln("    *,");
document.writeln("    *:before,");
document.writeln("    *:after {");
document.writeln("        box-sizing: border-box;");
document.writeln("        -webkit-box-sizing: border-box;");
document.writeln("        -moz-box-sizing: border-box;");
document.writeln("    }");
document.writeln("");
document.writeln("    html,");
document.writeln("    body,");
document.writeln("    div,");
document.writeln("    span,");
document.writeln("    object,");
document.writeln("    iframe,");
document.writeln("    h1,");
document.writeln("    h2,");
document.writeln("    h3,");
document.writeln("    h4,");
document.writeln("    h5,");
document.writeln("    h6,");
document.writeln("    p,");
document.writeln("    blockquote,");
document.writeln("    pre,");
document.writeln("    abbr,");
document.writeln("    address,");
document.writeln("    cite,");
document.writeln("    code,");
document.writeln("    del,");
document.writeln("    dfn,");
document.writeln("    em,");
document.writeln("    img,");
document.writeln("    ins,");
document.writeln("    kbd,");
document.writeln("    q,");
document.writeln("    samp,");
document.writeln("    small,");
document.writeln("    strong,");
document.writeln("    sub,");
document.writeln("    sup,");
document.writeln("    var,");
document.writeln("    b,");
document.writeln("    i,");
document.writeln("    dl,");
document.writeln("    dt,");
document.writeln("    dd,");
document.writeln("    ol,");
document.writeln("    ul,");
document.writeln("    li,");
document.writeln("    fieldset,");
document.writeln("    form,");
document.writeln("    label,");
document.writeln("    legend,");
document.writeln("    table,");
document.writeln("    caption,");
document.writeln("    tbody,");
document.writeln("    tfoot,");
document.writeln("    thead,");
document.writeln("    tr,");
document.writeln("    th,");
document.writeln("    td,");
document.writeln("    article,");
document.writeln("    aside,");
document.writeln("    canvas,");
document.writeln("    details,");
document.writeln("    figcaption,");
document.writeln("    figure,");
document.writeln("    footer,");
document.writeln("    header,");
document.writeln("    hgroup,");
document.writeln("    menu,");
document.writeln("    nav,");
document.writeln("    section,");
document.writeln("    summary,");
document.writeln("    time,");
document.writeln("    mark,");
document.writeln("    audio,");
document.writeln("    video,");
document.writeln("    form {");
document.writeln("        margin: 0;");
document.writeln("        padding: 0;");
document.writeln("        border: 0;");
document.writeln("        outline: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    input {");
document.writeln("        margin: 0;");
document.writeln("        padding: 0;");
document.writeln("        outline: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    li {");
document.writeln("        list-style: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    a,");
document.writeln("    ins {");
document.writeln("        text-decoration: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    *:focus {");
document.writeln("        outline: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    a {");
document.writeln("        color: #333;");
document.writeln("    }");
document.writeln("");
document.writeln("    /*颜色根据通用信息列表的文字颜色决定*/");
document.writeln("    .more a {");
document.writeln("        color: #999;");
document.writeln("        font-size: 16px;");
document.writeln("    }");
document.writeln("");
document.writeln("    /*颜色根据通用更多的文字颜色决定*/");
document.writeln("    a:hover {");
document.writeln("        color: #1b5c90;");
document.writeln("    }");
document.writeln("");
document.writeln("    /*颜色根据psd主色调决定，比如很多都是蓝色*/");
document.writeln("    .more a:hover {");
document.writeln("        color: #1b5c90;");
document.writeln("    }");
document.writeln("");
document.writeln("    /*颜色根据psd主色调决定，比如很多都是蓝色*/");
document.writeln("    .fl {");
document.writeln("        float: left;");
document.writeln("    }");
document.writeln("");
document.writeln("    .fr {");
document.writeln("        float: right;");
document.writeln("    }");
document.writeln("");
document.writeln("    .clear-fix:before {");
document.writeln("        content: \' \';");
document.writeln("        display: table;");
document.writeln("    }");
document.writeln("");
document.writeln("    .clear-fix:after {");
document.writeln("        content: \' \';");
document.writeln("        display: block;");
document.writeln("        clear: both;");
document.writeln("        height: 0;");
document.writeln("        visibility: hidden;");
document.writeln("    }");
document.writeln("");
document.writeln("    .cf:after {");
document.writeln("        display: block;");
document.writeln("        content: \'\';");
document.writeln("        height: 0;");
document.writeln("        visibility: hidden;");
document.writeln("        clear: both;");
document.writeln("    }");
document.writeln("");
document.writeln("    .cf {");
document.writeln("        zoom: 1;");
document.writeln("    }");
document.writeln("");
document.writeln("    .hide {");
document.writeln("        display: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    .block {");
document.writeln("        display: block;");
document.writeln("    }");
document.writeln("");
document.writeln("    a {");
document.writeln("        color: #333333;");
document.writeln("    }");
document.writeln("");
document.writeln("    a:hover {");
document.writeln("        color: #1d79cc;");
document.writeln("    }");
document.writeln("");
document.writeln("    html {");
document.writeln("        overflow-y: scroll;");
document.writeln("        height: 100%;");
document.writeln("    }");
document.writeln("");
document.writeln("    body {");
document.writeln("        font-family: 微软雅黑;");
document.writeln("        background: #fff;");
document.writeln("        min-width: 850px;");
document.writeln("        height: 100%;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_bg_con {");
document.writeln("        padding: 0;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_bg {");
document.writeln("        width: 100%;");
document.writeln("        min-height: auto;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu_bg {");
document.writeln("        background: #7694bf;");
document.writeln("        position: absolute;");
document.writeln("        width: 100%;");
document.writeln("        height: 100%;");
document.writeln("        left: 0px;");
document.writeln("        top: 0px;");
document.writeln("        z-index: 1;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_bg {");
document.writeln("        width: 100%;");
document.writeln("        background: url(/picture/0/a48eeb8177a342a9bdf44029f3d34de2.png) top center no-repeat;");
document.writeln("        background-size: 125%;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_con {");
document.writeln("        width: 1200px;");
document.writeln("        margin: 0 auto;");
document.writeln("        min-height: 200px;");
document.writeln("        position: relative;");
document.writeln("        z-index: 999;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* 无障碍适老化按钮 */");
document.writeln("    .top_con .top-btn .bt-right {");
document.writeln("        float: right;");
document.writeln("        font-size: 16px;");
document.writeln("        text-align: center;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_con .top-btn .bt-right .wza {");
document.writeln("        padding: 0px 15px;");
document.writeln("        float: left;");
document.writeln("        background-color: #4a7fb4;");
document.writeln("        height: auto;");
document.writeln("        line-height: 36px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_con .top-btn .bt-right .old {");
document.writeln("        padding: 0 10px;");
document.writeln("        float: left;");
document.writeln("        background-color: #ea9327;");
document.writeln("        cursor: pointer;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_con .top-btn .bt-right .old a {");
document.writeln("        font-size: 20px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_con .top-btn .bt-right .wza img {");
document.writeln("        width: 18px;");
document.writeln("        margin-right: 5px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .top_con .top-btn .bt-right a,");
document.writeln("    .top_con .top-btn .bt-right span {");
document.writeln("        color: #ffffff;");
document.writeln("        cursor: pointer;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* logo */");
document.writeln("    .top_logo {");
document.writeln("        width: 510px;");
document.writeln("        height: 95px;");
document.writeln("        position: absolute;");
document.writeln("        left: 0px;");
document.writeln("        top: 70px;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* 检索 */");
document.writeln("    .search {");
document.writeln("        width: 310px;");
document.writeln("        height: 40px;");
document.writeln("        position: absolute;");
document.writeln("        right: 0px;");
document.writeln("        bottom: 70px;");
document.writeln("        opacity: 0.8;");
document.writeln("    }");
document.writeln("");
document.writeln("    .search .search_tit {");
document.writeln("        width: 230px;");
document.writeln("        height: 40px;");
document.writeln("        line-height: 40px;");
document.writeln("        padding-left: 50px;");
document.writeln("        border: 0;");
document.writeln("        float: left;");
document.writeln("        outline: none;");
document.writeln("        font-size: 15px;");
document.writeln("        color: #999999;");
document.writeln("        background: url(/picture/0/73eaf2c208464b3897431c210290f680.png) no-repeat;");
document.writeln("    }");
document.writeln("");
document.writeln("    .search .search_btn {");
document.writeln("        width: 80px;");
document.writeln("        height: 40px;");
document.writeln("        float: left;");
document.writeln("        background: url(/picture/0/c78b2deea4634a089a5ecdf1f3894f2e.png) no-repeat;");
document.writeln("        border: 0;");
document.writeln("        cursor: pointer;");
document.writeln("        font-size: 17px;");
document.writeln("        color: #FFFFFF;");
document.writeln("    }");
document.writeln("");
document.writeln("    /*首页导航*/");
document.writeln("    .zx_menu {");
document.writeln("        width: 1200px;");
document.writeln("        /*position: relative;*/");
document.writeln("        margin: 0 auto;");
document.writeln("        overflow: hidden;");
document.writeln("        height: 50px;");
document.writeln("        /*z-index: 998;*/");
document.writeln("        background: #7694bf;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu ul li.hover {");
document.writeln("        background: #245399 !important;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu ul li:hover {");
document.writeln("        background: #4f73c5;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu .nav ul.open {");
document.writeln("        float: left;");
document.writeln("        width: 1200px;");
document.writeln("        position: relative;");
document.writeln("        z-index: 9;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu .nav ul.open li {");
document.writeln("        float: left;");
document.writeln("        width: 240px;");
document.writeln("        color: #fff;");
document.writeln("        font-size: 19px;");
document.writeln("        height: 50px;");
document.writeln("        line-height: 50px;");
document.writeln("        cursor: pointer;");
document.writeln("        border-left: 1px solid #e8e8e8;");
document.writeln("        position: relative;");
document.writeln("        display: block;");
document.writeln("        padding-left: 100px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu .nav ul.open:first-child {");
document.writeln("        border-left: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu .nav ul.open li:hover {");
document.writeln("        background-color: #c61f0c;");
document.writeln("        color: #fff;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu .nav ul.open li a {");
document.writeln("        color: #fff;");
document.writeln("        font-size: 19px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu .nav ul.open li span {");
document.writeln("        color: #fff;");
document.writeln("        font-size: 19px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu .nav ul.open li img {");
document.writeln("        width: 24px;");
document.writeln("        height: 24px;");
document.writeln("        position: absolute;");
document.writeln("        top: 13px;");
document.writeln("        left: 50px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zx_menu p {");
document.writeln("        float: left;");
document.writeln("        background: url(/picture/0/943c1d8f4d55413199ab60fb25f46e0e.png) center center no-repeat;");
document.writeln("        width: 50px;");
document.writeln("        height: 50px;");
document.writeln("        position: relative;");
document.writeln("        z-index: 9;");
document.writeln("        cursor: pointer;");
document.writeln("    }");
document.writeln("");
document.writeln("    #barrierfree_container {");
document.writeln("        height: 100%;");
document.writeln("    }");
document.writeln("");
document.writeln("    .backstretch {");
document.writeln("        min-width: 1200px !important;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* 适老化按钮 */");
document.writeln("    .old_type * {");
document.writeln("        cursor: url(/picture/0/f7da4854d662464a97007e72d0bf7680.png), auto !important;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .old_boount,");
document.writeln("    .old_type .seach_but,");
document.writeln("    .old_type .search input[type=submit],");
document.writeln("    .old_type .swiper-pagination-bullet,");
document.writeln("    .old_type a,");
document.writeln("    .old_type .wza span,");
document.writeln("    .old_type a img,");
document.writeln("    .old_type .yqlj span,");
document.writeln("    .old_type a span,");
document.writeln("    .old_type .jact_bnt_01New,");
document.writeln("    .old_type .rsetNew01,");
document.writeln("    .old_type .next,.old_type .printer,.old_type .close,");
document.writeln("    .old_type .prev {");
document.writeln("        cursor: url(/picture/0/efe304c804ed4085892839cff4f54862.png) 16 0, auto !important;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .new_boount {");
document.writeln("        display: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .old_boount {");
document.writeln("        display: block;");
document.writeln("    }");
document.writeln("");
document.writeln("    .zzms {");
document.writeln("        background: #ea9327;");
document.writeln("        display: block;");
document.writeln("        width: auto;");
document.writeln("        height: 36px;");
document.writeln("        line-height: 36px;");
document.writeln("        color: #fff;");
document.writeln("        /* font-weight: bold; */");
document.writeln("        font-size: 16px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .top-btn .bt-right .wza {");
document.writeln("        width: auto;");
document.writeln("        height: 64px;");
document.writeln("        line-height: 64px;");
document.writeln("        font-size: 32px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .top-btn .bt-right .wza span{");
document.writeln("        font-size: 32px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .top-btn .bt-right .wza img {");
document.writeln("        width: 35px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .top-btn .bt-right .old {");
document.writeln("        width: auto;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .top-btn .bt-right .old a{");
document.writeln("        font-size: 32px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_boount {");
document.writeln("        display: none;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .old_boount {");
document.writeln("        display: block;");
document.writeln("        height: 64px;");
document.writeln("        line-height: 64px;");
document.writeln("        border-radius: 8px;");
document.writeln("        padding: 0 15px;");
document.writeln("        font-size: 32px;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .search {");
document.writeln("        width: 400px;");
document.writeln("        height: 80px;");
document.writeln("        right: 0px;");
document.writeln("        bottom: 70px;");
document.writeln("        opacity: 1;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .search .search_tit {");
document.writeln("        width: 300px;");
document.writeln("        height: 80px;");
document.writeln("        line-height: 80px;");
document.writeln("        padding-left: 20px;");
document.writeln("        font-size: 30px;");
document.writeln("        color: #999999;");
document.writeln("        background: #ffffff;");
document.writeln("    }");
document.writeln("");
document.writeln("    .old_type .search .search_btn {");
document.writeln("        width: 100px;");
document.writeln("        height: 80px;");
document.writeln("        background: #dc9438;");
document.writeln("        font-size: 30px;");
document.writeln("    }");
document.writeln("");
document.writeln("    /* 适老化导航 */");
document.writeln("    .old_type .top_bg{");
document.writeln("        background-size: 145%;");
document.writeln("    }");
document.writeln("    .old_type .top_con{");
document.writeln("        min-height: 250px;");
document.writeln("    }");
document.writeln("    .old_type .top_logo{");
document.writeln("        top: 85px;");
document.writeln("        width: 600px;");
document.writeln("    }");
document.writeln("    .old_type .top_logo img{");
document.writeln("        width: 100%;;");
document.writeln("    }");
document.writeln("    .old_type .zx_menu {");
document.writeln("        height: 70px;");
document.writeln("    }");
document.writeln("    .old_type .zx_menu .nav ul.open li {");
document.writeln("        float: left;");
document.writeln("        width: 240px;");
document.writeln("        color: #fff;");
document.writeln("        font-size: 32px;");
document.writeln("        height: 70px;");
document.writeln("        line-height: 70px;");
document.writeln("        text-align: center;");
document.writeln("        padding: 0;");
document.writeln("    }");
document.writeln("    .old_type .zx_menu .nav ul.open li a,.old_type .zx_menu .nav ul.open li span {");
document.writeln("        font-size: 32px;");
document.writeln("    }");
document.writeln("    .old_type .zx_menu .nav ul.open li img {");
document.writeln("        display: none;");
document.writeln("    }");
document.writeln("");
document.writeln(".old_type .zx_menu_con{");
document.writeln("    box-shadow: 0 2px 15px 0 rgba(153,153,153,0.2);");
document.writeln("}");
document.writeln("</style>");
document.writeln("<div class=\"top_con cf\">");
document.writeln("    <div class=\"top-btn cf\">");
document.writeln("        <div class=\"bt-right cf\">");
document.writeln("            <div class=\"wza\" ergodic=\"serve\" barrierfree_zone_dsc=\"当前为顶部服务区。无障碍浏览按钮\"><img src=\"/picture/0/ae65cdbdd2d44869a7463d542f4c06d3.png\" width=\"15\">");
document.writeln("                <span href=\"javascript:;\" onclick=\"toggleToolBar();\">无障碍浏览</span>");
document.writeln("            </div>");
document.writeln("            <div class=\"old\" ergodic=\"serve\" barrierfree_zone_dsc=\"当前为顶部服务区。长者浏览模式按钮\">");
document.writeln("                <a class=\"new_boount zzms\">进入长者浏览模式</a>");
document.writeln("                <a class=\"old_boount zzms\">退出长者浏览模式</a>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"top_logo\"><a href=\"/index.html\"><img src=\"/picture/0/fcdd425ffdf8416fbeb35fedc0df2dcd.png\"></a></div>");
document.writeln("    <div class=\"search\" ergodic=\"serve\" barrierfree_zone_dsc=\"当前为服务区，检索功能区域\">");
document.writeln("        <form id=\"SearchForm\" name=\"search-form\" action=\"http://www.jiangsu.gov.cn/jrobot/search.do\" method=\"get\"");
document.writeln("            target=\"_blank\">");
document.writeln("            <input name=\"webid\" type=\"hidden\" value=\"34\">");
document.writeln("            <input id=\"pg\" name=\"pg\" type=\"hidden\" value=\"12\">");
document.writeln("            <input id=\"p\" name=\"p\" type=\"hidden\" value=\"1\">");
document.writeln("            <input name=\"tpl\" type=\"hidden\" value=\"2\">");
document.writeln("            <input name=\"od\" type=\"hidden\" value=\"1\">");
document.writeln("            <input id=\"category\" name=\"category\" type=\"hidden\" value=\"\">");
document.writeln("            <input type=\"text\" class=\"search_tit\" name=\"q\" id=\"q\"");
document.writeln("                onfocus=\"if(this.value==\'请输入搜索关键词\') {this.value=\'\';this.focus();}\"");
document.writeln("                onblur=\"if(this.value==\'\'){this.value=\'请输入搜索关键词\'}\" value=\"请输入搜索关键词\">");
document.writeln("            <input type=\"submit\" class=\"search_btn\" value=\"搜索\">");
document.writeln("        </form>");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<!--首页导航-->");
document.writeln("<div class=\"zx_menu\" ergodic=\"navigation\" bfr_zone_dsc tabindex=\'0\' barrierfree_zone_dsc=\"导航区，当前为主导航区，有首页、信息公开、网上办事、互动交流、专题专栏等栏目\">");
document.writeln("   <!-- <div class=\"zx_menu_bg\"></div> -->");
document.writeln("    <div class=\"nav\">");
document.writeln("        <ul class=\"open\">");
document.writeln("            <li><a href=\"/index.html\"><img src=\"/picture/0/e0ff70b6e26c42d19a03d1b435eab761.png\"");
document.writeln("                        alt=\"\"><span>网站首页</span></a></li>");
document.writeln("            <li><a href=\"/col/col49350/index.html\"><img src=\"/picture/0/80251b13773c40e69ed7d65fd8fcbda6.png\"");
document.writeln("                        alt=\"\"><span>信息公开</span></a></li>");
document.writeln("            <li><a href=\"/col/col75700/index.html\"><img src=\"/picture/0/88ad19d490b3485bb83199bd180e7f08.png\"");
document.writeln("                        alt=\"\"><span>网上办事</span></a></li>");
document.writeln("            <li><a href=\"/col/col75701/index.html\"><img src=\"/picture/0/cb3c1a8a5cdc4270abfbfdf619c96b91.png\"");
document.writeln("                        alt=\"\"><span>互动交流</span></a></li>");
document.writeln("            <li><a href=\"/col/col75702/index.html\"><img src=\"/picture/0/4d1313a9b8d64a1a923742a048b2c2e8.png\"");
document.writeln("                        alt=\"\"><span>专题专栏</span></a></li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("</div>");
$('.search_btn').click(function(){
    var xx=$('.search_tit').val();
    if(xx=='请输入搜索关键词'){
        alert('请输入搜索关键词')
        return false;
    }else{
        return true;
    }
});