document.writeln("	<style type=\'text/css\'>");
document.writeln("		* {");
document.writeln("			margin: 0;");
document.writeln("			padding: 0;");
document.writeln("		}");
document.writeln("");
document.writeln("		ul,");
document.writeln("		li {");
document.writeln("			list-style: none;");
document.writeln("		}");
document.writeln("");
document.writeln("		a {");
document.writeln("			text-decoration: none;");
document.writeln("		}");
document.writeln("");
document.writeln("		/* 底部 */");
document.writeln("		.box-top {");
document.writeln("			width: 1200px;");
document.writeln("			margin: 0 auto;");
document.writeln("		}");
document.writeln("");
document.writeln("		a:hover {");
document.writeln("			text-decoration: none !important;");
document.writeln("		}");
document.writeln("");
document.writeln("		/* .fl {");
document.writeln("			float: left;");
document.writeln("		} */");
document.writeln("");
document.writeln("		.fr {");
document.writeln("			float: right;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj {");
document.writeln("			width: 100%;");
document.writeln("			/* min-width: 1200px; */");
document.writeln("			height: 60px;");
document.writeln("			/* margin-top: 20px; */");
document.writeln("			background-color: #daecfb;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj>ul {");
document.writeln("			text-align: center;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj>ul>li {");
document.writeln("			display: inline-block;");
document.writeln("			position: relative;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj>ul>li>a {");
document.writeln("			padding: 0 38px;");
document.writeln("			font-size: 16px;");
document.writeln("			line-height: 60px;");
document.writeln("			color: #115db2;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj span {");
document.writeln("			display: inline-block;");
document.writeln("			*zoom: 1;");
document.writeln("			*display: inline;");
document.writeln("			padding: 0 35px;");
document.writeln("			background: url(http://www.yantai.gov.cn/picture/83/2108091715102145353.png) right center no-repeat;");
document.writeln("			font-size: 16px;");
document.writeln("			line-height: 60px;");
document.writeln("			color: #115db2;");
document.writeln("			text-align: center;");
document.writeln("			cursor: pointer;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj .on span {");
document.writeln("			background: url(http://www.yantai.gov.cn/picture/83/2108091715101576781.png) right center no-repeat;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj>ul>li ul {");
document.writeln("			display: none;");
document.writeln("			width: 188px;");
document.writeln("			height: 280px;");
document.writeln("			background: #fff;");
document.writeln("			border: 1px solid #ccc;");
document.writeln("			font-size: 14px;");
document.writeln("			line-height: 28px;");
document.writeln("			overflow-y: auto;");
document.writeln("			position: absolute;");
document.writeln("			top: -280px;");
document.writeln("			left: 0;");
document.writeln("			z-index: 99999999;");
document.writeln("			margin: 0;");
document.writeln("			padding: 0;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj>ul>li ul li {");
document.writeln("			padding: 0 10px;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj>ul>li ul li:hover {");
document.writeln("			background: #ccc;");
document.writeln("		}");
document.writeln("");
document.writeln("		.yqlj>ul>li ul li a {");
document.writeln("			line-height: 28px;");
document.writeln("			color: #333;");
document.writeln("			font-size: 14px;");
document.writeln("		}");
document.writeln("");
document.writeln("		.footer {");
document.writeln("			width: 100%;");
document.writeln("			/* min-width: 1200px; */");
document.writeln("			/* height: 120px; */");
document.writeln("			background-color: #115db2;");
document.writeln("			padding: 50px 0;");
document.writeln("		}");
document.writeln("");
document.writeln("		.footer .box-top {");
document.writeln("			width: 1200px;");
document.writeln("			height: 100%;");
document.writeln("			margin: 0 auto;");
document.writeln("			display: flex;");
document.writeln("			justify-content: center;");
document.writeln("		}");
document.writeln("");
document.writeln("		.dzjg {");
document.writeln("			margin: 24px 0 0 30px;");
document.writeln("		}");
document.writeln("");
document.writeln("		.jc {");
document.writeln("			margin: 35px 0 0 30px;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info {");
document.writeln("			padding: 0;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info li {");
document.writeln("			float: left;");
document.writeln("			border-left: 1px solid #417dc1;");
document.writeln("			border-right: 1px solid #417dc1;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info001 {");
document.writeln("			margin-left: 35px;");
document.writeln("			padding: 0 10px 0 45px;");
document.writeln("			font-size: 16px;");
document.writeln("			line-height: 28px;");
document.writeln("			color: #fff;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info001 .split_span {");
document.writeln("			font-size: 16px !important;");
document.writeln("			color: #fff !important;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info001 a {");
document.writeln("			display: inline-block;");
document.writeln("			font-size: 16px;");
document.writeln("			line-height: 32px;");
document.writeln("			color: #fff !important;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info001 a img {}");
document.writeln("");
document.writeln("		.info001 span {");
document.writeln("			margin-right: 5px;");
document.writeln("			font-size: 16px;");
document.writeln("			color: #ffffff;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info001 p {");
document.writeln("			margin: 0;");
document.writeln("			font-size: 16px;");
document.writeln("			color: #ffffff;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info002 {");
document.writeln("			padding-left: 20px;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info002 p {");
document.writeln("			margin-right: 16px;");
document.writeln("			font-size: 14px;");
document.writeln("			line-height: 28px;");
document.writeln("			color: #fff;");
document.writeln("			text-align: center;");
document.writeln("			margin-top: 0;");
document.writeln("		}");
document.writeln("");
document.writeln("		.info002 p img {");
document.writeln("			width: 100px;");
document.writeln("			height: 100px;");
document.writeln("		}");
document.writeln("");
document.writeln("		.ewm {");
document.writeln("			display: flex;");
document.writeln("			padding-left: 40px;");
document.writeln("		}");
document.writeln("");
document.writeln("		.ewm p{");
document.writeln("			font-size: 14px;");
document.writeln("			color: #fff;");
document.writeln("			text-align: center;");
document.writeln("		}");
document.writeln("");
document.writeln("		.ewm img {");
document.writeln("			width: 100px;");
document.writeln("			height: 100px;");
document.writeln("		}");
document.writeln("		.ewm div:first-child{");
document.writeln("			margin-right: 15px;");
document.writeln("		}");
document.writeln("");
document.writeln("");
document.writeln("		@media screen and (max-width: 1200px) {");
document.writeln("");
document.writeln("			.yqlj ul {");
document.writeln("				width: 100%;");
document.writeln("				overflow: hidden;");
document.writeln("			}");
document.writeln("");
document.writeln("			.yqlj>ul>li {");
document.writeln("				width: 15%;");
document.writeln("				text-align: center;");
document.writeln("			}");
document.writeln("");
document.writeln("			.yqlj>ul>li:first-child {");
document.writeln("				width: 10%;");
document.writeln("			}");
document.writeln("");
document.writeln("			.yqlj>ul>li>a {");
document.writeln("				padding: 0 10px;");
document.writeln("				font-size: 0.5rem;");
document.writeln("			}");
document.writeln("");
document.writeln("			.yqlj span {");
document.writeln("				padding-left: 0;");
document.writeln("				padding-right: 15px;");
document.writeln("				font-size: 0.5rem;");
document.writeln("			}");
document.writeln("");
document.writeln("			.dzjg {");
document.writeln("				margin: 24px 0 0 10px;");
document.writeln("				display: none;");
document.writeln("			}");
document.writeln("			.ewm{");
document.writeln("				display: none;");
document.writeln("			}");
document.writeln("");
document.writeln("			.jc {");
document.writeln("				margin: 35px 0 0 10px;");
document.writeln("				display: none;");
document.writeln("			}");
document.writeln("");
document.writeln("			.footer {");
document.writeln("				overflow: hidden;");
document.writeln("				width: 100%;");
document.writeln("			}");
document.writeln("");
document.writeln("			.footer .box-top {");
document.writeln("				overflow: hidden;");
document.writeln("				width: 100%;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info001 {");
document.writeln("				margin-left: 15px;");
document.writeln("				padding: 0 20px;");
document.writeln("				font-size: 14px;");
document.writeln("				line-height: 28px;");
document.writeln("				color: #fff;");
document.writeln("				/* width: 50%; */");
document.writeln("			}");
document.writeln("");
document.writeln("			.info002 {");
document.writeln("				display: none;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info {");
document.writeln("				margin: auto;");
document.writeln("				float: none;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info li {");
document.writeln("				border: none;");
document.writeln("				text-align: center;");
document.writeln("				width: 100%;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info001 p img {");
document.writeln("				/* line-height: 20px; */");
document.writeln("				margin-top: -5px;");
document.writeln("				margin-right: 5px;");
document.writeln("				margin-left: 5px;");
document.writeln("			}");
document.writeln("");
document.writeln("		}");
document.writeln("");
document.writeln("		@media screen and (max-width: 800px) {");
document.writeln("			.yqlj {");
document.writeln("				display: none !important;");
document.writeln("			}");
document.writeln("");
document.writeln("			.footer {");
document.writeln("				height: auto;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info {");
document.writeln("				height: auto;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info li {");
document.writeln("				width: 90%;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info001 {");
document.writeln("				margin: auto;");
document.writeln("				text-align: -webkit-match-parent;");
document.writeln("				display: inline-block;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info001 p span {");
document.writeln("				margin: 0 10px;");
document.writeln("				box-sizing: border-box;");
document.writeln("				display: inline-block;");
document.writeln("			}");
document.writeln("");
document.writeln("			.info001 p img {");
document.writeln("				margin-top: -5px;");
document.writeln("				margin-right: 5px;");
document.writeln("			}");
document.writeln("		}");
document.writeln("	</style>");
document.writeln("	<div class=\'yqlj\'>");
document.writeln("		<ul class=\'box-top clearfix\'>");
document.writeln("			<li>");
document.writeln("				<a target=\'_blank\' href=\'http://www.gov.cn\'>中国政府网</a>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<span>国务院部门网站</span>");
document.writeln("				<ul>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.fmprc.gov.cn/web/\' target=\'_blank\' title=\'外交部\'");
document.writeln("							style=\'outline: none;\'>外交部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mod.gov.cn/\' target=\'_blank\' title=\'国防部\'");
document.writeln("							style=\'outline: none;\'>国防部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ndrc.gov.cn/\' target=\'_blank\' title=\'国家发展和改革委员会\'");
document.writeln("							style=\'outline: none;\'>国家发展和改革委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.moe.gov.cn/\' target=\'_blank\' title=\'教育部\'");
document.writeln("							style=\'outline: none;\'>教育部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.most.gov.cn/\' target=\'_blank\' title=\'科学技术部\'");
document.writeln("							style=\'outline: none;\'>科学技术部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.miit.gov.cn/\' target=\'_blank\' title=\'工业和信息化部\'");
document.writeln("							style=\'outline: none;\'>工业和信息化部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.seac.gov.cn/\' target=\'_blank\' title=\'国家民族事务委员会\'");
document.writeln("							style=\'outline: none;\'>国家民族事务委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mps.gov.cn/\' target=\'_blank\' title=\'公安部\'");
document.writeln("							style=\'outline: none;\'>公安部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mca.gov.cn/\' target=\'_blank\' title=\'民政部\'");
document.writeln("							style=\'outline: none;\'>民政部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.moj.gov.cn/\' target=\'_blank\' title=\'司法部\'");
document.writeln("							style=\'outline: none;\'>司法部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mof.gov.cn/\' target=\'_blank\' title=\'财政部\'");
document.writeln("							style=\'outline: none;\'>财政部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mohrss.gov.cn/\' target=\'_blank\' title=\'人力资源社会保障部\'");
document.writeln("							style=\'outline: none;\'>人力资源社会保障部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mnr.gov.cn\' target=\'_blank\' title=\'自然资源部\'");
document.writeln("							style=\'outline: none;\'>自然资源部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mee.gov.cn\' target=\'_blank\' title=\'生态环境部\'");
document.writeln("							style=\'outline: none;\'>生态环境部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mohurd.gov.cn/\' target=\'_blank\' title=\'住房和城乡建设部\'");
document.writeln("							style=\'outline: none;\'>住房和城乡建设部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mot.gov.cn/\' target=\'_blank\' title=\'交通运输部\'");
document.writeln("							style=\'outline: none;\'>交通运输部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mwr.gov.cn/\' target=\'_blank\' title=\'水利部\'");
document.writeln("							style=\'outline: none;\'>水利部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.moa.gov.cn/\' target=\'_blank\' title=\'农业农村部\'");
document.writeln("							style=\'outline: none;\'>农业农村部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mofcom.gov.cn/\' target=\'_blank\' title=\'商务部\'");
document.writeln("							style=\'outline: none;\'>商务部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mct.gov.cn/\' target=\'_blank\' title=\'文化和旅游部\'");
document.writeln("							style=\'outline: none;\'>文化和旅游部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.nhc.gov.cn/\' target=\'_blank\' title=\'国家卫生健康委员会\'");
document.writeln("							style=\'outline: none;\'>国家卫生健康委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mva.gov.cn/\' target=\'_blank\' title=\'退役军人事务部\'");
document.writeln("							style=\'outline: none;\'>退役军人事务部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mem.gov.cn/\' target=\'_blank\' title=\'应急管理部\'");
document.writeln("							style=\'outline: none;\'>应急管理部</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.pbc.gov.cn/\' target=\'_blank\' title=\'人民银行\'");
document.writeln("							style=\'outline: none;\'>人民银行</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.audit.gov.cn/\' target=\'_blank\' title=\'审计署\'");
document.writeln("							style=\'outline: none;\'>审计署</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.moe.gov.cn/jyb_sy/China_Language/\' target=\'_blank\'");
document.writeln("							title=\'国家语言文字工作委员会\' style=\'outline: none;\'>国家语言文字工作委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.safea.gov.cn/\' target=\'_blank\' title=\'国家外国专家局\'");
document.writeln("							style=\'outline: none;\'>国家外国专家局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cnsa.gov.cn/\' target=\'_blank\' title=\'国家航天局\'");
document.writeln("							style=\'outline: none;\'>国家航天局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.caea.gov.cn/\' target=\'_blank\' title=\'国家原子能机构\'");
document.writeln("							style=\'outline: none;\'>国家原子能机构</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'' target=\'_blank\' title=\'国家海洋局\'");
document.writeln("							style=\'outline: none;\'>国家海洋局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://nnsa.mee.gov.cn/\' target=\'_blank\' title=\'国家核安全局\'");
document.writeln("							style=\'outline: none;\'>国家核安全局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.sasac.gov.cn/\' target=\'_blank\' title=\'国务院国有资产监督管理委员会\'");
document.writeln("							style=\'outline: none;\'>国务院国有资产监督管理委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.customs.gov.cn/\' target=\'_blank\' title=\'海关总署\'");
document.writeln("							style=\'outline: none;\'>海关总署</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.chinatax.gov.cn/\' target=\'_blank\' title=\'国家税务总局\'");
document.writeln("							style=\'outline: none;\'>国家税务总局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.samr.gov.cn\' target=\'_blank\' title=\'国家市场监督管理总局\'");
document.writeln("							style=\'outline: none;\'>国家市场监督管理总局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.nrta.gov.cn/\' target=\'_blank\' title=\'国家广播电视总局\'");
document.writeln("							style=\'outline: none;\'>国家广播电视总局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.sport.gov.cn/\' target=\'_blank\' title=\'国家体育总局\'");
document.writeln("							style=\'outline: none;\'>国家体育总局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.stats.gov.cn/\' target=\'_blank\' title=\'国家统计局\'");
document.writeln("							style=\'outline: none;\'>国家统计局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.counsellor.gov.cn/\' target=\'_blank\' title=\'国务院参事室\'");
document.writeln("							style=\'outline: none;\'>国务院参事室</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ggj.gov.cn/\' target=\'_blank\' title=\'国家机关事务管理局\'");
document.writeln("							style=\'outline: none;\'>国家机关事务管理局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cnca.gov.cn/\' target=\'_blank\' title=\'国家认证认可监督管理委员会\'");
document.writeln("							style=\'outline: none;\'>国家认证认可监督管理委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.sac.gov.cn/\' target=\'_blank\' title=\'国家标准化管理委员会\'");
document.writeln("							style=\'outline: none;\'>国家标准化管理委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ncac.gov.cn/\' target=\'_blank\' title=\'国家新闻出版署（国家版权局）\'");
document.writeln("							style=\'outline: none;\'>国家新闻出版署（国家版权局）</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.sara.gov.cn/\' target=\'_blank\' title=\'国家宗教事务局\'");
document.writeln("							style=\'outline: none;\'>国家宗教事务局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.hmo.gov.cn/\' target=\'_blank\' title=\'国务院港澳事务办公室\'");
document.writeln("							style=\'outline: none;\'>国务院港澳事务办公室</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gov.cn/guoqing/2018-06/22/content_5300522.htm\'");
document.writeln("							target=\'_blank\' title=\'国务院研究室\' style=\'outline: none;\'>国务院研究室</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gqb.gov.cn/\' target=\'_blank\' title=\'国务院侨务办公室\'");
document.writeln("							style=\'outline: none;\'>国务院侨务办公室</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gwytb.gov.cn/\' target=\'_blank\' title=\'国务院台湾事务办公室\'");
document.writeln("							style=\'outline: none;\'>国务院台湾事务办公室</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cac.gov.cn/\' target=\'_blank\' title=\'国家互联网信息办公室\'");
document.writeln("							style=\'outline: none;\'>国家互联网信息办公室</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.scio.gov.cn/index.htm\' target=\'_blank\'");
document.writeln("							title=\'国务院新闻办公室\' style=\'outline: none;\'>国务院新闻办公室</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://203.192.6.89/xhs/\' target=\'_blank\' title=\'新华通讯社\'");
document.writeln("							style=\'outline: none;\'>新华通讯社</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cas.ac.cn/\' target=\'_blank\' title=\'中国科学院\'");
document.writeln("							style=\'outline: none;\'>中国科学院</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cssn.cn/\' target=\'_blank\' title=\'中国社会科学院\'");
document.writeln("							style=\'outline: none;\'>中国社会科学院</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cae.cn/\' target=\'_blank\' title=\'中国工程院\'");
document.writeln("							style=\'outline: none;\'>中国工程院</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.drc.gov.cn/\' target=\'_blank\' title=\'国务院发展研究中心\'");
document.writeln("							style=\'outline: none;\'>国务院发展研究中心</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cma.gov.cn/\' target=\'_blank\' title=\'中国气象局\'");
document.writeln("							style=\'outline: none;\'>中国气象局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cbirc.gov.cn/cn/view/pages/index/index.html' target=\'_blank\'");
document.writeln("							title=\'中国银行保险监督管理委员会\' style=\'outline: none;\'>中国银行保险监督管理委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.csrc.gov.cn/pub/newsite/\' target=\'_blank\'");
document.writeln("							title=\'中国证券监督管理委员会\' style=\'outline: none;\'>中国证券监督管理委员会</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ccps.gov.cn/\' target=\'_blank\' title=\'国家行政学院\'");
document.writeln("							style=\'outline: none;\'>国家行政学院</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gjxfj.gov.cn/\' target=\'_blank\' title=\'国家信访局\'");
document.writeln("							style=\'outline: none;\'>国家信访局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.lswz.gov.cn/' target=\'_blank\'");
document.writeln("							title=\'国家粮食和物资储备局\' style=\'outline: none;\'>国家粮食和物资储备局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.nea.gov.cn/\' target=\'_blank\' title=\'国家能源局\'");
document.writeln("							style=\'outline: none;\'>国家能源局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.sastind.gov.cn/\' target=\'_blank\' title=\'国家国防科技工业局\'");
document.writeln("							style=\'outline: none;\'>国家国防科技工业局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.tobacco.gov.cn/html/\' target=\'_blank\' title=\'国家烟草专卖局\'");
document.writeln("							style=\'outline: none;\'>国家烟草专卖局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.mps.gov.cn/n2254996/\' target=\'_blank\' title=\'国家移民管理局\'");
document.writeln("							style=\'outline: none;\'>国家移民管理局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.forestry.gov.cn/\' target=\'_blank\' title=\'国家林业和草原局\'");
document.writeln("							style=\'outline: none;\'>国家林业和草原局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.nra.gov.cn/\' target=\'_blank\' title=\'国家铁路局\'");
document.writeln("							style=\'outline: none;\'>国家铁路局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.caac.gov.cn/index.html\' target=\'_blank\'");
document.writeln("							title=\'中国民用航空局\' style=\'outline: none;\'>中国民用航空局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.spb.gov.cn/\' target=\'_blank\' title=\'国家邮政局\'");
document.writeln("							style=\'outline: none;\'>国家邮政局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ncha.gov.cn/\' target=\'_blank\' title=\'国家文物局\'");
document.writeln("							style=\'outline: none;\'>国家文物局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.satcm.gov.cn/\' target=\'_blank\' title=\'国家中医药管理局\'");
document.writeln("							style=\'outline: none;\'>国家中医药管理局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'https://www.chinamine-safety.gov.cn/\' target=\'_blank\'");
document.writeln("							title=\'国家煤矿安全监察局\' style=\'outline: none;\'>国家煤矿安全监察局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.safe.gov.cn/\' target=\'_blank\' title=\'国家外汇管理局\'");
document.writeln("							style=\'outline: none;\'>国家外汇管理局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.nmpa.gov.cn/\' target=\'_blank\' title=\'国家药品监督管理局\'");
document.writeln("							style=\'outline: none;\'>国家药品监督管理局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cnipa.gov.cn/\' target=\'_blank\' title=\'国家知识产权局\'");
document.writeln("							style=\'outline: none;\'>国家知识产权局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.forestry.gov.cn/\' target=\'_blank\' title=\'国家公园管理局\'");
document.writeln("							style=\'outline: none;\'>国家公园管理局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.scs.gov.cn/\' target=\'_blank\' title=\'国家公务员局\'");
document.writeln("							style=\'outline: none;\'>国家公务员局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.saac.gov.cn/\' target=\'_blank\' title=\'国家档案局\'");
document.writeln("							style=\'outline: none;\'>国家档案局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.oscca.gov.cn/\' target=\'_blank\' title=\'国家密码管理局\'");
document.writeln("							style=\'outline: none;\'>国家密码管理局</a></li>");
document.writeln("");
document.writeln("");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<span>省政府网站</span>");
document.writeln("				<ul>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.beijing.gov.cn/\' target=\'_blank\' title=\'北京\'");
document.writeln("							style=\'outline: none;\'>北京</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.tj.gov.cn/\' target=\'_blank\' title=\'天津\'");
document.writeln("							style=\'outline: none;\'>天津</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.hebei.gov.cn/\' target=\'_blank\' title=\'河北\'");
document.writeln("							style=\'outline: none;\'>河北</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.shanxi.gov.cn/\' target=\'_blank\' title=\'山西\'");
document.writeln("							style=\'outline: none;\'>山西</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.nmg.gov.cn/\' target=\'_blank\' title=\'内蒙古\'");
document.writeln("							style=\'outline: none;\'>内蒙古</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ln.gov.cn/\' target=\'_blank\' title=\'辽宁\'");
document.writeln("							style=\'outline: none;\'>辽宁</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.jl.gov.cn/\' target=\'_blank\' title=\'吉林\'");
document.writeln("							style=\'outline: none;\'>吉林</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.hlj.gov.cn/\' target=\'_blank\' title=\'黑龙江\'");
document.writeln("							style=\'outline: none;\'>黑龙江</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.shanghai.gov.cn/\' target=\'_blank\' title=\'上海\'");
document.writeln("							style=\'outline: none;\'>上海</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.jiangsu.gov.cn/\' target=\'_blank\' title=\'江苏\'");
document.writeln("							style=\'outline: none;\'>江苏</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.zj.gov.cn/\' target=\'_blank\' title=\'浙江\'");
document.writeln("							style=\'outline: none;\'>浙江</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ah.gov.cn/\' target=\'_blank\' title=\'安徽\'");
document.writeln("							style=\'outline: none;\'>安徽</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.fujian.gov.cn/\' target=\'_blank\' title=\'福建\'");
document.writeln("							style=\'outline: none;\'>福建</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.jiangxi.gov.cn/\' target=\'_blank\' title=\'江西\'");
document.writeln("							style=\'outline: none;\'>江西</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.shandong.gov.cn/\' target=\'_blank\' title=\'山东\'");
document.writeln("							style=\'outline: none;\'>山东</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.henan.gov.cn/\' target=\'_blank\' title=\'河南\'");
document.writeln("							style=\'outline: none;\'>河南</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.hubei.gov.cn/\' target=\'_blank\' title=\'湖北\'");
document.writeln("							style=\'outline: none;\'>湖北</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.hunan.gov.cn/\' target=\'_blank\' title=\'湖南\'");
document.writeln("							style=\'outline: none;\'>湖南</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gd.gov.cn/\' target=\'_blank\' title=\'广东\'");
document.writeln("							style=\'outline: none;\'>广东</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gxzf.gov.cn/\' target=\'_blank\' title=\'广西\'");
document.writeln("							style=\'outline: none;\'>广西</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.hainan.gov.cn/\' target=\'_blank\' title=\'海南\'");
document.writeln("							style=\'outline: none;\'>海南</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.cq.gov.cn/\' target=\'_blank\' title=\'重庆\'");
document.writeln("							style=\'outline: none;\'>重庆</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.sc.gov.cn/\' target=\'_blank\' title=\'四川\'");
document.writeln("							style=\'outline: none;\'>四川</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.guizhou.gov.cn/\' target=\'_blank\' title=\'贵州\'");
document.writeln("							style=\'outline: none;\'>贵州</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.yn.gov.cn/\' target=\'_blank\' title=\'云南\'");
document.writeln("							style=\'outline: none;\'>云南</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.xizang.gov.cn/\' target=\'_blank\' title=\'西藏\'");
document.writeln("							style=\'outline: none;\'>西藏</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.shaanxi.gov.cn/\' target=\'_blank\' title=\'陕西\'");
document.writeln("							style=\'outline: none;\'>陕西</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gansu.gov.cn/\' target=\'_blank\' title=\'甘肃\'");
document.writeln("							style=\'outline: none;\'>甘肃</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.qinghai.gov.cn/\' target=\'_blank\' title=\'青海\'");
document.writeln("							style=\'outline: none;\'>青海</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.nx.gov.cn/\' target=\'_blank\' title=\'宁夏\'");
document.writeln("							style=\'outline: none;\'>宁夏</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.xinjiang.gov.cn/\' target=\'_blank\' title=\'新疆\'");
document.writeln("							style=\'outline: none;\'>新疆</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gov.hk/\' target=\'_blank\' title=\'香港\'");
document.writeln("							style=\'outline: none;\'>香港</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.gov.mo/\' target=\'_blank\' title=\'澳门\'");
document.writeln("							style=\'outline: none;\'>澳门</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'' target=\'_blank\' title=\'台湾\'");
document.writeln("							style=\'outline: none;\'>台湾</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.xjbt.gov.cn/\' target=\'_blank\' title=\'新疆生产建设兵团\'");
document.writeln("							style=\'outline: none;\'>新疆生产建设兵团</a></li>");
document.writeln("");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<span>省内地市级网站</span>");
document.writeln("				<ul>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.jinan.gov.cn/index.html\' class=\'bt_link\'");
document.writeln("							target=\'_blank\' title=\'济南市\' style=\'outline: none;\'>济南市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.qingdao.gov.cn\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'青岛市\' style=\'outline: none;\'>青岛市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.zibo.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'淄博市\' style=\'outline: none;\'>淄博市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.zaozhuang.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'枣庄市\' style=\'outline: none;\'>枣庄市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.dongying.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'东营市\' style=\'outline: none;\'>东营市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.weifang.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'潍坊市\' style=\'outline: none;\'>潍坊市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.jining.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'济宁市\' style=\'outline: none;\'>济宁市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.taian.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'泰安市\' style=\'outline: none;\'>泰安市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.weihai.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'威海市\' style=\'outline: none;\'>威海市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.rizhao.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'日照市\' style=\'outline: none;\'>日照市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.binzhou.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'滨州市\' style=\'outline: none;\'>滨州市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.dezhou.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'德州市\' style=\'outline: none;\'>德州市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.liaocheng.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'聊城市\' style=\'outline: none;\'>聊城市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.linyi.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'临沂市\' style=\'outline: none;\'>临沂市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.heze.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'菏泽市\' style=\'outline: none;\'>菏泽市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.laiwu.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							title=\'莱芜市(原)\' style=\'outline: none;\'>莱芜市(原)</a></li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<span>市政府部门网站</span>");
document.writeln("				<ul>");
document.writeln("					<li style=\'outline: none;\'><a href=\'https://www.yantai.gov.cn \' target=\'_blank\' \'=\'\' class=\' bt_link\'");
document.writeln("							tabindex=\'0\' aria-label=\'烟台市政府网站\' style=\'outline: none;\'>烟台市政府网站</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://fgw.yantai.gov.cn \' target=\'_blank\' \'=\'\' class=\' bt_link\'");
document.writeln("							tabindex=\'0\' aria-label=\'市发展改革委\' style=\'outline: none;\'>市发展改革委</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://jyj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市教育局\' style=\'outline: none;\'>市教育局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://kjj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市科技局\' style=\'outline: none;\'>市科技局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://jxw.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市工业和信息化局\' style=\'outline: none;\'>市工业和信息化局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://mzj.yantai.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							tabindex=\'0\' aria-label=\'市民政局\' style=\'outline: none;\'>市民政局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://gaj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市公安局\' style=\'outline: none;\'>市公安局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://sfj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市司法局\' style=\'outline: none;\'>市司法局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://czj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市财政局\' style=\'outline: none;\'>市财政局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://rshj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市人力资源社会保障局\' style=\'outline: none;\'>市人力资源社会保障局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://gtj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市自然资源和规划局\' style=\'outline: none;\'>市自然资源和规划局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://hbj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市生态环境局\' style=\'outline: none;\'>市生态环境局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://zjj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市住房城乡建设局\' style=\'outline: none;\'>市住房城乡建设局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://cgj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市城管局\' style=\'outline: none;\'>市城管局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://jtj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市交通运输局\' style=\'outline: none;\'>市交通运输局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://slj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市水利局\' style=\'outline: none;\'>市水利局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://nongye.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市农业农村局\' style=\'outline: none;\'>市农业农村局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://hyj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市海洋发展和渔业局\' style=\'outline: none;\'>市海洋发展和渔业局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://swj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市商务局\' style=\'outline: none;\'>市商务局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://whlyj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市文化和旅游局\' style=\'outline: none;\'>市文化和旅游局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://wjw.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市卫生健康委\' style=\'outline: none;\'>市卫生健康委</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.yantai.gov.cn/col/col33890/index.html \'");
document.writeln("							target=\'_blank\' \'=\'\' class=\' bt_link\' tabindex=\'0\' aria-label=\'市退役军人局\'");
document.writeln("							style=\'outline: none;\'>市退役军人局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://yjj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市应急局\' style=\'outline: none;\'>市应急局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://sjj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市审计局\' style=\'outline: none;\'>市审计局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://wb.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市外办\' style=\'outline: none;\'>市外办</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://gzw.yantai.gov.cn \' target=\'_blank\' \'=\'\' class=\' bt_link\'");
document.writeln("							tabindex=\'0\' aria-label=\'市国资委\' style=\'outline: none;\'>市国资委</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://spj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市行政审批服务局\' style=\'outline: none;\'>市行政审批服务局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://scjgj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市市场监管局\' style=\'outline: none;\'>市市场监管局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://tyj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市体育局\' style=\'outline: none;\'>市体育局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://tjj.yantai.gov.cn \' target=\'_blank\' \'=\'\' class=\' bt_link\'");
document.writeln("							tabindex=\'0\' aria-label=\'市统计局\' style=\'outline: none;\'>市统计局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://ybj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市医保局\' style=\'outline: none;\'>市医保局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://jgswj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市机关事务局\' style=\'outline: none;\'>市机关事务局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://rfb.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市人防办\' style=\'outline: none;\'>市国动办</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.yantai.gov.cn/col/col12176/index.html\'");
document.writeln("							class=\'bt_link\' target=\'_blank\' tabindex=\'0\' aria-label=\'市地方金融监管局\'");
document.writeln("							style=\'outline: none;\'>市地方金融监管局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://dsjj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市大数据局\' style=\'outline: none;\'>市大数据局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://xfj.yantai.gov.cn \' target=\'_blank\' \'=\'\' class=\' bt_link\'");
document.writeln("							tabindex=\'0\' aria-label=\'市信访局\' style=\'outline: none;\'>市信访局</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://idb.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市投资促进中心\' style=\'outline: none;\'>市投资促进中心</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://gjj.yantai.gov.cn/ \' target=\'_blank\' \'=\'\' class=\'");
document.writeln("							bt_link\' tabindex=\'0\' aria-label=\'市住房公积金管理中心\' style=\'outline: none;\'>市住房公积金管理中心</a></li>");
document.writeln("");
document.writeln("");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li>");
document.writeln("				<span>区市政府网站</span>");
document.writeln("				<ul>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.zhifu.gov.cn\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'芝罘区\' style=\'outline: none;\'>芝罘区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ytfushan.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'福山区\' style=\'outline: none;\'>福山区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ytlaishan.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'莱山区\' style=\'outline: none;\'>莱山区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.muping.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'牟平区\' style=\'outline: none;\'>牟平区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.penglai.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'蓬莱区\' style=\'outline: none;\'>蓬莱区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.haiyang.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'海阳市\' style=\'outline: none;\'>海阳市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.laiyang.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'莱阳市\' style=\'outline: none;\'>莱阳市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.sdqixia.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'栖霞市\' style=\'outline: none;\'>栖霞市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.longkou.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'龙口市\' style=\'outline: none;\'>龙口市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.zhaoyuan.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'招远市\' style=\'outline: none;\'>招远市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.laizhou.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'莱州市\' style=\'outline: none;\'>莱州市</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.yeda.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'黄渤海新区\' style=\'outline: none;\'>黄渤海新区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.ytgxq.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'高新区\' style=\'outline: none;\'>高新区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://bsgq.yantai.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'保税港区\' style=\'outline: none;\'>保税港区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://www.changdao.gov.cn/\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'长岛综合试验区\' style=\'outline: none;\'>长岛综合试验区</a></li>");
document.writeln("					<li style=\'outline: none;\'><a href=\'http://kys.yantai.gov.cn\' class=\'bt_link\' target=\'_blank\'");
document.writeln("							aria-label=\'昆嵛山保护区\' style=\'outline: none;\'>昆嵛山保护区</a></li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("			<li style=\'display: none;\'>");
document.writeln("				<span>新闻媒体网站</span>");
document.writeln("				<ul>");
document.writeln("					<li>");
document.writeln("						<a href=\'\'>新闻媒体网站</a>");
document.writeln("					</li>");
document.writeln("				</ul>");
document.writeln("			</li>");
document.writeln("		</ul>");
document.writeln("	</div>");
document.writeln("	<div class=\'footer\'>");
document.writeln("		<div class=\'box-top clearfix\'>");
document.writeln("			<div class=\'dzjg fl\'>");
document.writeln("				<a href=\'http://bszs.conac.cn/sitename?method=show&id=538CADD4B5020796E053022819ACF75E\'><img");
document.writeln("						src=\'http://www.yantai.gov.cn/picture/83/2108091715100736128.png\'></a>");
document.writeln("			</div>");
document.writeln("			<div class=\'jc fl\' id=\'_span_jiucuo\'>");
document.writeln("				<a href=\'https://zfwzzc.www.gov.cn/check_web/errorInfo/jcInfoNew?siteCode=3706000055&url=http%3A%2F%2Fzjj.yantai.gov.cn%2Fcol%2Fcol31992%2Findex.html\'><img src=\'http://www.yantai.gov.cn/picture/83/2108091715099987145.png\'></a>");
document.writeln("			</div>");
document.writeln("			<ul class=\'info fl\'>");
document.writeln("				<li class=\'info001\'>");
document.writeln("					<p>");
document.writeln("						<a target=\'_blank\' href=\'http://zjj.yantai.gov.cn/col/col22903/index.html\'>网站地图</a>  <a target=\'_blank\' href=\'//zjj.yantai.gov.cn/\'>中文域名:烟台市住房和城乡建设局.政务</a>");
document.writeln("					</p>");
document.writeln("					<p>烟台市住房和城乡建设局版权所有 未经许可，不得转载、复制和建立镜像</p>");
document.writeln("					<p>地址：烟台市莱山区观海路23号 联系电话：6905956   邮编：264003 </p>");
document.writeln("					<p>");
document.writeln("						<span>");
document.writeln("							<a href=\'https://beian.miit.gov.cn\' target=\'_blank\'>鲁ICP备09096174号-7</a>");
document.writeln("						</span>");
document.writeln("						<span>网站标识码：3706000055</span>");
document.writeln("						<span>");
document.writeln("							<a href=\'http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=37061302000316\'");
document.writeln("								target=\'_blank\'><img src=\'http://www.yantai.gov.cn/picture/83/2108091715099611454.png\'");
document.writeln("									width=\'13\' height=\'14\'> 鲁公网安备 37061302000316号</a>");
document.writeln("						</span>");
document.writeln("					</p>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("			<div class=\'ewm\'>");
document.writeln("				<div>");
document.writeln("					<img src=\'http://zjj.yantai.gov.cn/picture/95/2111052018434506858.png\' alt=\'\'>");
document.writeln("					<p>烟台住建</p>");
document.writeln("				</div>");
document.writeln("				<!-- <div>");
document.writeln("					<img src=\'http://www.laiyang.gov.cn/picture/72/2109091030014636464.png\' alt=\'\'>");
document.writeln("					<p>政务微博</p>");
document.writeln("				</div> -->");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("	<script id=\'_jiucuo_\' sitecode=\'3706000055\' src=\'https://zfwzgl.www.gov.cn/exposure/jiucuo.js\'></script>");
document.writeln("	<script type=\'text/javascript\'>");
document.writeln("		$(\'.yqlj>ul>li\').each(function () {");
document.writeln("			$(this).hover(function () {");
document.writeln("				$(this).find(\'ul\').show().parent().siblings().find(\'ul\').hide();");
document.writeln("				$(this).addClass(\'on\').siblings().removeClass(\'on\');");
document.writeln("			}, function () {");
document.writeln("				$(\'.yqlj>ul>li ul\').hide();");
document.writeln("				$(\'.yqlj>ul>li\').removeClass(\'on\');");
document.writeln("			});");
document.writeln("		});");
document.writeln("	</script>");
document.writeln("<script id=\'barrierfree\' src=\'/accessiblereading/load.js\'></script>");